spring:
  application:
    name: learn

  datasource:
    url: jdbc:h2:mem:~/supwayApiTest
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      # 스프링부트에서 인식하는 sql파일 schema.sql, data.sql 자동실행
      # -> 네이밍 변경원하면 schema-locations, data-locations 속성추가
      mode: always
  h2:
    console:
      enabled: true  # H2 콘솔 활성화
      path: /h2-console  # 웹에서 http://localhost:8080/h2-console 로 접속 가능
      settings:
        web-allow-others: true

# yml 파일은 띄어쓰기와 들여쓰기가 중요하다. 여기서 seoul을 들여쓰기로 해두면 spring: 하위에 속한거로 인식해서 인식이 안된다.
seoul:
  api:
    key: "794b577059796b6d3930444165706a"  # 발급받은 API 키

